Notebook 02 — Data Understanding

Step 1 — Dataset Information

In [6]:
import pandas as pd

# Assuming you have a CSV file, replace 'your_dataset.csv' with your actual file path
df = pd.read_csv('/content/Bank_Churn_Classification_Dataset.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10000 non-null  int64
 1   CustomerID      10000 non-null  int64
 2   Gender          10000 non-null  object
 3   SeniorCitizen   10000 non-null  int64
 4   Tenure          10000 non-null  int64
 5   MonthlyCharges  10000 non-null  float64
 6   Contract        10000 non-null  object
 7   PaymentMethod   10000 non-null  object
 8   Churn           10000 non-null  int64
 9   TotalCharges    10000 non-null  float64
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

Step 2 — Data Types

In [7]:
df.dtypes

Unnamed: 0          int64
CustomerID          int64
Gender             object
SeniorCitizen       int64
Tenure              int64
MonthlyCharges    float64
Contract           object
PaymentMethod      object
Churn               int64
TotalCharges      float64
dtype: object

Step 3 — Statistical Summary

Numerical Columns

In [8]:
df.describe()

,Unnamed: 0,CustomerID,SeniorCitizen,Tenure,MonthlyCharges,Churn,TotalCharges
count,10000.00000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4999.50000,4999.50000,0.499300,35.955000,70.451038,0.267000,2541.807390
std,2886.89568,2886.89568,0.500025,20.501761,28.935692,0.442414,1879.645307
min,0.00000,0.00000,0.000000,1.000000,20.000000,0.000000,21.200000
25%,2499.75000,2499.75000,0.000000,18.000000,45.527500,0.000000,1035.057500
50%,4999.50000,4999.50000,0.000000,36.000000,70.585000,0.000000,2117.135000
75%,7499.25000,7499.25000,1.000000,54.000000,95.612500,1.000000,3717.352500
max,9999.00000,9999.00000,1.000000,71.000000,120.000000,1.000000,8384.390000

All Columns (including Categorical)

In [9]:
df.describe(include='all')

,Unnamed: 0,CustomerID,Gender,SeniorCitizen,Tenure,MonthlyCharges,Contract,PaymentMethod,Churn,TotalCharges
count,10000.00000,10000.00000,10000,10000.000000,10000.000000,10000.000000,10000,10000,10000.000000,10000.000000
unique,NaN,NaN,2,NaN,NaN,NaN,3,4,NaN,NaN
top,NaN,NaN,Male,NaN,NaN,NaN,One year,Electronic check,NaN,NaN
freq,NaN,NaN,5013,NaN,NaN,NaN,3455,2516,NaN,NaN
mean,4999.50000,4999.50000,NaN,0.499300,35.955000,70.451038,NaN,NaN,0.267000,2541.807390
std,2886.89568,2886.89568,NaN,0.500025,20.501761,28.935692,NaN,NaN,0.442414,1879.645307
min,0.00000,0.00000,NaN,0.000000,1.000000,20.000000,NaN,NaN,0.000000,21.200000
25%,2499.75000,2499.75000,NaN,0.000000,18.000000,45.527500,NaN,NaN,0.000000,1035.057500
50%,4999.50000,4999.50000,NaN,0.000000,36.000000,70.585000,NaN,NaN,0.000000,2117.135000
75%,7499.25000,7499.25000,NaN,1.000000,54.000000,95.612500,NaN,NaN,1.000000,3717.352500
max,9999.00000,9999.00000,NaN,1.000000,71.000000,120.000000,NaN,NaN,1.000000,8384.390000

Step 4 — Unique Value Counts

In [11]:
for col in df.columns:
    print(f'\n{col}')
    print('Unique Values:', df[col].nunique())

Unnamed: 0
Unique Values: 10000

CustomerID
Unique Values: 10000

Gender
Unique Values: 2

SeniorCitizen
Unique Values: 2

Tenure
Unique Values: 71

MonthlyCharges
Unique Values: 6302

Contract
Unique Values: 3

PaymentMethod
Unique Values: 4

Churn
Unique Values: 2

TotalCharges
Unique Values: 9723

Step 5 — Sample Values

In [12]:
for col in df.columns:
   print('\n', col)
   print(df[col].unique()[:10])

 Unnamed: 0
[0 1 2 3 4 5 6 7 8 9]

 CustomerID
[0 1 2 3 4 5 6 7 8 9]

 Gender
['Male' 'Female']

 SeniorCitizen
[0 1]

 Tenure
[55 36 37 14 27 31 44 68 48 57]

 MonthlyCharges
[111.88  58.7  118.86  96.14  28.05  86.02  47.08  44.37  45.66 111.61]

 Contract
['Two year' 'One year' 'Month-to-month']

 PaymentMethod
['Mailed check' 'Electronic check' 'Bank transfer' 'Credit card']

 Churn
[0 1]

 TotalCharges
[6153.4  2113.2  4397.82 1345.96  757.35 2666.62 2071.52 3017.16 2191.68
 6361.77]

Step 6 — Feature Summary Table

In [14]:
summary = pd.DataFrame({
    'Column': df.columns,
    'DataType': df.dtypes.values,
    'MissingValues': df.isnull().sum().values,
    'UniqueValues': df.nunique().values
})
summary

           Column DataType  MissingValues  UniqueValues
0      Unnamed: 0    int64              0         10000
1      CustomerID    int64              0         10000
2          Gender   object              0             2
3   SeniorCitizen    int64              0             2
4          Tenure    int64              0            71
5  MonthlyCharges  float64              0          6302
6        Contract   object              0             3
7   PaymentMethod   object              0             4
8           Churn    int64              0             2
9    TotalCharges  float64              0          9723

Step 7 — Identify Feature Types

In [16]:
import numpy as np

numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(include=['object','category']).columns

print('Numerical Features')
print(list(numeric_cols))
print('\nCategorical Features')
print(list(categorical_cols))

Numerical Features
['Unnamed: 0', 'CustomerID', 'SeniorCitizen', 'Tenure', 'MonthlyCharges', 'Churn', 'TotalCharges']

Categorical Features
['Gender', 'Contract', 'PaymentMethod']